### ISSUE TITLE
Cannot read property 'storageOpts' of undefined

### ISSUE THREAD

**Issue by mubasshir** [jeffminsungkim/nestjs-multer-extended#171]
```
TypeError: Cannot read property 'storageOpts' of undefined
    at MixinInterceptor.pickStorageOptions (/project/node_modules/nestjs-multer-extended/dist/interceptors/amazon-s3-file.interceptor.js:68:112)
    at MixinInterceptor.<anonymous> (/project/node_modules/nestjs-multer-extended/dist/interceptors/amazon-s3-file.interceptor.js:42:48)
    at Generator.next (<anonymous>)
    at /project/node_modules/nestjs-multer-extended/dist/interceptors/amazon-s3-file.interceptor.js:20:71
    at new Promise (<anonymous>)
    at __awaiter (/project/node_modules/nestjs-multer-extended/dist/interceptors/amazon-s3-file.interceptor.js:16:12)
    at MixinInterceptor.intercept (/project/node_modules/nestjs-multer-extended/dist/interceptors/amazon-s3-file.interceptor.js:39:20)
    at /project/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:22:36
    at Object.handle (/project/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:20:56)
    at CacheInterceptor.intercept (/project/node_modules/@nestjs/common/cache/interceptors/cache.interceptor.js:19:25)
```
Did I miss anything?

**Comment by jeffminsungkim** [comment]
Can you please show me how you imported the module?

**Comment by mubasshir** [comment]
**app.module.ts**
```
.
.
.

MulterExtendedModule.registerAsync({
      useFactory: (config: ConfigService) => config.get('s3'),
      inject: [ConfigService],
    }),
.
.
.

```

**config/s3.ts**
```
export default {
    accessKeyId: process.env.S3_ACCESS_KEY,
    secretAccessKey: process.env.S3_ACCESS_SECRET,
    region: process.env.S3_REGION,
    bucket: process.env.S3_BUCKET,
    fileSize: +process.env.S3_MAX_FILE_LIMIT * 1024 * 1024,
    acl: 'public-read',
};

```

**Comment by jeffminsungkim** [comment]
Could you please show me the entire code from a `app.module.ts` file?

**Comment by mubasshir** [comment]
```
@Module({
  imports: [
    ConfigModule,
    ConfigModule.load(
      path.resolve(__dirname, 'config', '**', '!(*.d).{ts,js}'),
      {
        path: path.resolve(process.cwd(), 'env', !ENV ? '.env' : `.env.${ENV}`),
      },
    ),
    TypeOrmModule.forRootAsync({
      useFactory: (config: ConfigService) => config.get('database'),
      inject: [ConfigService],
    }),
    MulterExtendedModule.registerAsync({
      useFactory: (config: ConfigService) => config.get('s3'),
      inject: [ConfigService],
    }),
    PassportModule.register({ defaultStrategy: 'jwt' }),
    JwtModule.register(JWT_MODULE_OPTIONS),
    CacheModule.registerAsync({
      imports: [ConfigModule],
      useFactory: async (config: ConfigService) => config.get('cache'),
      inject: [ConfigService],
    }),
    HttpModule,
    ...
],
})
export class AppModule { }
```

**Comment by jeffminsungkim** [comment]
You should import the `MulterExtendedModule` on the same level where the controller wants to use it. (Solved it from VS Live Share)

**Comment by mubasshir** [comment]
thank you @jeffminsungkim , you were very kind & helpful

**Comment by Utzel-Butzel** [comment]
Sorry, I was unable to resolve the issue. Can you please explain what is meant by importing `MulterExtendedModule` on the same level where the controller is?
Many thanks for the package and all your work!

**Comment by ideenkreise** [comment]
> Sorry, I was unable to resolve the issue. Can you please explain what is meant by importing `MulterExtendedModule` on the same level where the controller is? Many thanks for the package and all your work!

Were u able to fix this issue.?

**Comment by premdasvm** [comment]
> 
> 
> Sorry, I was unable to resolve the issue. Can you please explain what is meant by importing `MulterExtendedModule` on the same level where the controller is? Many thanks for the package and all your work!

Were you able to fix this issue.?

**Comment by premdasvm** [comment]
> 
> 
> thank you @jeffminsungkim , you were very kind & helpful

Hey mate, How did he fix it.?
