### ISSUE TITLE
Use parameters with file upload

### ISSUE THREAD

**Issue by klalex** [jeffminsungkim/nestjs-multer-extended#183]
I'm trying to use param with file upload and getting the following exception:

/Users/alex/Projects/AlumniAces-Backend/node_modules/nestjs-multer-extended/dist/multer-config.loader.js:42
                cb(null, basePath);
                ^
TypeError: Cannot read property 'length' of undefined
    at /Users/alex/Projects/AlumniAces-Backend/node_modules/nestjs-multer-extended/dist/multer-sharp/multer-sharp.js:69:72
    at Object.Key (/Users/alex/Projects/AlumniAces-Backend/node_modules/nestjs-multer-extended/dist/multer-config.loader.js:42:17)
    at MulterSharp._handleFile (/Users/alex/Projects/AlumniAces-Backend/node_modules/nestjs-multer-extended/dist/multer-sharp/multer-sharp.js:58:25)
    at /Users/alex/Projects/AlumniAces-Backend/node_modules/multer/lib/make-middleware.js:144:17
    at filterImageFileExtension (/Users/alex/Projects/AlumniAces-Backend/node_modules/nestjs-multer-extended/dist/multer-config.loader.js:64:16)
    at wrappedFileFilter (/Users/alex/Projects/AlumniAces-Backend/node_modules/multer/index.js:44:7)
    at Busboy.<anonymous> (/Users/alex/Projects/AlumniAces-Backend/node_modules/multer/lib/make-middleware.js:114:7)
    at Busboy.emit (events.js:209:13)
    at Busboy.EventEmitter.emit (domain.js:476:20)
    at Busboy.emit (/Users/alex/Projects/AlumniAces-Backend/node_modules/busboy/lib/main.js:38:33)

Example of action code:

```
@Post('/:postId')
    @ApiConsumes('multipart/form-data')
    @ApiFile('file') 
    @ApiParam({
        name: 'postId',
        required: true,
        type: String
    })
    @UseInterceptors(
        AmazonS3FileInterceptor('file', {
            randomFilename: true
        }),
    )
    upload(@Param('postId') postId: string, @UploadedFile() file) {
        console.log(file);
        console.log(postId);
    }
```

**Comment by jeffminsungkim** [comment]
Can you provide a minimum reproduction repository?

**Comment by klalex** [comment]
Here you are.
[Archive.zip](https://github.com/jeffminsungkim/nestjs-multer-extended/files/4908051/Archive.zip)

**Comment by jeffminsungkim** [comment]
@klalex 
You should add `dynamicPath` property in order to accept the path parameter.
For your case you should fix your code as follows:

```typescript
@Post('/:postId')
    @ApiConsumes('multipart/form-data')
    @ApiFile('file') 
    @ApiParam({
        name: 'postId',
        required: true,
        type: String
    })
    @UseInterceptors(
        AmazonS3FileInterceptor('file', {
            randomFilename: true,
            dynamicPath: 'postId'
        }),
    )
    upload(@Param('postId') postId: string, @UploadedFile() file) {
        console.log(file);
        console.log(postId);
    }
```
